name: flutter_network_speed_test
description: A library for testing internet speed.
version: 0.1.1
repository: https://github.com/zaikir/flutter_speed_test

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  dio: ^5.7.0
  pool: ^1.5.1
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
