name: flutter_speed_test
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  dio: ^5.7.0
  pool: ^1.5.1
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
